
DROP TABLE prueba;
create table prueba(
	ID VARCHAR(50) PRIMARY KEY,
	USUARIO VARCHAR(100) NOT NULL,
	CLIENTE VARCHAR(100) NOT NULL,
	DNI VARCHAR(20) NOT NULL,
	TELEFONO VARCHAR(20) NOT NULL,
	DISTRITO VARCHAR(50)  NULL,
	DIRECCION VARCHAR(150)  NULL,
	CLASIFICACION VARCHAR(200) NOT NULL,
	NRO_CLASIFICACION INT NULL,
	FECHA DATETIME NOT NULL,
	REFERIDO CHAR(2) NULL,
	BLOQUEADO CHAR(2) NULL,
	BASE_ADMI VARCHAR(50) NULL,
	COMENTARIOS_ADMI VARCHAR(300) NULL,
	OBSERVACIONES_USU VARCHAR(300) NULL
)
